# Generated by Django 4.2.4 on 2023-08-03 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tienda.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('fotos', models.ImageField(blank=True, null=True, upload_to=tienda.models.productos_directory_path)),
                ('categoria', models.CharField(choices=[('COSMÉTICOS', 'Cosméticos'), ('FLORES', 'Flores'), ('ROPA', 'Ropa'), ('COMESTIBLES', 'Comestibles'), ('VARIOS', 'Varios')], default='FLORES', max_length=15)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Precio_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.SmallIntegerField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
        ),
    ]
