# Generated by Django 4.2.4 on 2023-08-08 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_precio_stock_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio_stock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='tienda.producto'),
        ),
    ]
